//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijoPortal {
    
    
    public partial class mrp_preview {

        protected global::AjaxControlToolkit.ModalPopupExtender ModalPopupExtenderLoading;

        /// <summary>
        /// LogsPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        /// 
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl mrpHead;

        protected global::DevExpress.Web.ASPxPopupControl LogsPopup;

        protected global::DevExpress.Web.ASPxPopupControl PopupSubmitPreview;
        
        /// <summary>
        /// LogsMemo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxMemo LogsMemo;
        
        /// <summary>
        /// LogsBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton LogsBtn;

        protected global::DevExpress.Web.ASPxButton btAddEdit;

        /// <summary>
        /// dvContentWrapper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvContentWrapper;
        
        /// <summary>
        /// DocNum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel DocNum;

        protected global::DevExpress.Web.ASPxLabel Creator;

        protected global::DevExpress.Web.ASPxLabel Status;

        /// <summary>
        /// Month control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel Month;
        
        /// <summary>
        /// EntityCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel EntityCode;
        
        /// <summary>
        /// Year control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel Year;
        
        /// <summary>
        /// BUCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel BUCode;
        
        /// <summary>
        /// tblSummCost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable tblSummCost;
        
        /// <summary>
        /// PreviewListSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView PreviewListSummary;
        
        /// <summary>
        /// TotalAmountSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TotalAmountSummary;
        
        /// <summary>
        /// MatListview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView MatListview;
        
        /// <summary>
        /// extraDMTD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell extraDMTD;
        
        /// <summary>
        /// TAMat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TAMat, LabelTotalDM;
        
        /// <summary>
        /// OpexListiview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView OpexListiview;
        
        /// <summary>
        /// extraOPTD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell extraOPTD;
        
        /// <summary>
        /// TAOpex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TAOpex, LabelTotalOP;
        
        /// <summary>
        /// ManListview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView ManListview;
        
        /// <summary>
        /// extraMANTD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell extraMANTD;
        
        /// <summary>
        /// TAManpower control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TAManpower, LabelTotalManpower;
        
        /// <summary>
        /// CapexListview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView CapexListview;
        
        /// <summary>
        /// extraCATD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell extraCATD;
        
        /// <summary>
        /// TotalAmountTD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TotalAmountTD, LabelTotalCapex;
        
        /// <summary>
        /// RevListview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView RevListview;
        
        /// <summary>
        /// TARevenue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TARevenue, LabelTARev;

        protected global::DevExpress.Web.ASPxHiddenField StatusHidden;
        protected global::DevExpress.Web.ASPxHiddenField WrkFlowHidden;
        protected global::DevExpress.Web.ASPxButton Submit;
        protected global::DevExpress.Web.ASPxPopupControl MRPNotify;
        protected global::DevExpress.Web.ASPxLabel MRPNotificationMessage;
        protected global::DevExpress.Web.ASPxPopupControl MRPAccessRights;
        protected global::DevExpress.Web.ASPxLabel MRPAccessRightsMsg;

        protected global::DevExpress.Web.ASPxGridView GridPreviewDM;
        protected global::DevExpress.Web.ASPxGridView GridPreviewOP;
        protected global::DevExpress.Web.ASPxGridView GridPreviewMAN;
        protected global::DevExpress.Web.ASPxGridView GridPreviewCA;
        protected global::DevExpress.Web.ASPxGridView GridPreviewREV;
        protected global::DevExpress.Web.ASPxGridView GridPreviewSummary;

        protected global::DevExpress.Web.ASPxRoundPanel RevRoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel DMRoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel CARoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel OPRoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel MANRoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel TotalRoundPanel;
        protected global::DevExpress.XtraReports.Web.ASPxWebDocumentViewer WebDocViewPrev;
        //protected global::DevExpress.Web.ASPxSpreadsheet.ASPxSpreadsheet SpreadsheetPreview;
    }
}
