//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijoPortal
{
    public partial class mrp_preview_inventanalyst
    {

        protected global::AjaxControlToolkit.ModalPopupExtender ModalPopupExtenderLoading;

        protected global::DevExpress.Web.ASPxPopupControl MRPNotify;
        protected global::DevExpress.Web.ASPxLabel MRPNotificationMessage;

        protected global::DevExpress.Web.ASPxPopupControl PopupSubmitPreviewAnal;
        /// <summary>
        /// dvContentWrapper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl mrpHead;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvContentWrapper;

        /// <summary>
        /// DocNum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel DocNum;

        protected global::DevExpress.Web.ASPxLabel Creator;

        protected global::DevExpress.Web.ASPxLabel Status;
        /// <summary>
        /// StatusHidden control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxHiddenField StatusHidden;
        protected global::DevExpress.Web.ASPxHiddenField WrkFlowHidden;

        /// <summary>
        /// btAddEdit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton btAddEdit;

        /// <summary>
        /// Submit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton Submit;

        /// <summary>
        /// Month control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel Month;

        /// <summary>
        /// EntityCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel EntityCode;

        /// <summary>
        /// Year control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel Year;

        /// <summary>
        /// BUCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel BUCode;

        /// <summary>
        /// RevListView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView RevListView;
        protected global::System.Web.UI.WebControls.ListView SummaryListView;
        protected global::System.Web.UI.WebControls.ListView DMListView, OpexListView, ManListView, CapexListView;
        /// <summary>
        /// extraRevTD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell
            extraRevTD, extraCATD, extraDMTD, extraOPTD,
            extraMANTD;
        //protected global::System.Web.UI.HtmlControls.HtmlTableCell extraRevTD;

        /// <summary>
        /// TARevenue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::DevExpress.Web.ASPxGridView GridPreviewDM;
        protected global::DevExpress.Web.ASPxGridView GridPreviewOP;
        protected global::DevExpress.Web.ASPxGridView GridPreviewMAN;
        protected global::DevExpress.Web.ASPxGridView GridPreviewCA;
        protected global::DevExpress.Web.ASPxGridView GridPreviewREV;
        protected global::DevExpress.Web.ASPxGridView GridPreviewSummary;

        protected global::DevExpress.Web.ASPxRoundPanel RevRoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel DMRoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel CARoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel OPRoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel MANRoundPanel;
        protected global::DevExpress.Web.ASPxRoundPanel TotalRoundPanel;

    }
}
